### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by DanielSokil** [beyonk-adventures/svelte-carousel#1]
Thanks for this component!

Any plans to put on NPM?
There is a similar project to this one on NPM: https://github.com/sciactive/multicarousel
But it seems to be abandoned, so it would be nice to see this one on NPM.

**Comment by antony** [comment]
Hi, sorry just spotted this!

I'm working on it right now - once I'm happy with how it works as a third-party component / js component - I'll publish to github.

Thanks!

**Comment by antony** [comment]
https://www.npmjs.com/package/@beyonk/svelte-carousel
