### ISSUE TITLE
rollup: not found

### ISSUE THREAD

**Issue by vovs03** [beyonk-adventures/svelte-carousel#10]
# :warning: rollup: not found

Hi! I want just how it works.

1. I clonned [this](https://github.com/beyonk-adventures/svelte-carousel) `repository`
2. And I send `npm run dev`

> :question: What me did it wrong?

![Screenshot from 2019-11-02 20-22-21](https://user-images.githubusercontent.com/21124057/68074706-2a29d700-fdaf-11e9-84f0-961bbbea4fbf.png)

**Comment by antony** [comment]
You need to install the dependencies. `npm install`, then it will work :)
