### ISSUE TITLE
How do you style pagination?

### ISSUE THREAD

**Issue by mxmzb** [beyonk-adventures/svelte-carousel#17]
I can style pagination to some extent via `:global()` selector, but how can I target the **current** dot?

**Comment by mxmzb** [comment]
On the same note, I am wondering how to change hover color on control icons:
```
<Carousel on:change={handleSlideChange} perPage={1}>
  <span class="control left-control" slot="left-control">
    <ChevronLeftIcon size="54" /> <!-- change icon color on hover? --> 
  </span>

  <div class="slide-content">
    <img class="mock" src="/images/screenshot-1.png" alt="" />
  </div>
  <div class="slide-content">
    <img class="mock" src="/images/screenshot-3.png" alt="" />
  </div>
  <div class="slide-content">
    <img class="mock" src="/images/screenshot-4.png" alt="" />
  </div>
  <div class="slide-content">
    <img class="mock" src="/images/screenshot-5.png" alt="" />
  </div>

  <span class="control" slot="right-control">
    <ChevronRightIcon size="54" />
  </span>
</Carousel>
```

**Comment by antony** [comment]
@mxmzb right now, we don't differentiate between the current dot, and all the other dots.

https://github.com/beyonk-adventures/svelte-carousel/blob/master/src/Carousel.svelte#L60

It would be possible I believe, by creating a small PR to track which dot was the currrent one, and maybe adding a class to it.

**Comment by mxmzb** [comment]
Silly me! I'll jump on it right away! 🤙
