### ISSUE TITLE
Not vanilla-js

### ISSUE THREAD

**Issue by varlevi** [beyonk-adventures/svelte-carousel#19]
Hi! On your site you have a vanilla-js tag. However, this project is focused on Svelte, a JS Framework. In order to make sure your project is correctly described, could you remove that tag?

**Comment by antony** [comment]
> Hi! On your site you have a vanilla-js tag. However, this project is focused on Svelte, a JS Framework. In order to make sure your project is correctly described, could you remove that tag?

Hi Varlevi. Svelte is what the component is written in, but Svelte is a compiler, not a framework, and as such, compiles to vanilla javascript. 

Because of this, the component is equally as usable in vanilla javascript as it is in any Svelte, React, Vue, or any other type of app.

**Comment by varlevi** [comment]
Huh. I had a different understanding of Svelte. Thank you for the correction. Nice project!
