### ISSUE TITLE
Invalid Svelte Usage Docs

### ISSUE THREAD

**Issue by DanielSokil** [beyonk-adventures/svelte-carousel#2]
When using this lib with Svelte as described with the readme, results in `Slide component is not defined` error.

This is how It worked for me, similar to [app/component.svelte](https://github.com/beyonk-adventures/svelte-carousel/blob/master/src/components/app/component.svelte)
```javascript
<Carousel current="3">
	<Slide>
		<h2>1</h2>
	</Slide>
	<Slide>
		<h2>2</h2>
	</Slide>
	<Slide>
		<h2>3</h2>
	</Slide>
	<Slide>
		<h2>4</h2>
	</Slide>
	<Slide>
		<h2>5</h2>
	</Slide>
	<Slide>
		<h2>6</h2>
	</Slide>
</Carousel>


<script>
  import Carousel from "node_modules/@beyonk/svelte-carousel/src/components/carousel/component.svelte";
  import Slide from "node_modules/@beyonk/svelte-carousel/src/components/slide/component.svelte";

  export default {
    components: {
      Carousel,
      Slide
    }
  };
</script>
```

**Comment by antony** [comment]
I ran into this myself - I had misunderstood how the 'svelte' attribute works in `package.json`. I'll update the docs accordingly.
