### ISSUE TITLE
sapper goto function says `Cannot read property 'removeChild' of null`

### ISSUE THREAD

**Issue by itswadesh** [beyonk-adventures/svelte-carousel#24]
```
import { goto } from '@sapper/app'
goto('blog')
```

Error
----------
`Cannot read property 'removeChild' of null`

**Comment by antony** [comment]
@itswadesh I'd need to see more code than that.

It sounds like you've either installed the carousel incorrectly (make sure it's in devDependencies), or you're using it incorrectly in your page.

**Comment by itswadesh** [comment]
@antony I created a default sapper setup with rollup + svelte carousel https://github.com/itswadesh/sapper-carousel

```
<script>
  import Carousel from "@beyonk/svelte-carousel";
  import { ChevronLeftIcon, ChevronRightIcon } from "svelte-feather-icons";
</script>

<Carousel>
  <div class="slide-content">Slide 1</div>
  <div class="slide-content">Slide 2</div>
  <div class="slide-content">Slide 3</div>
  <div class="slide-content">Slide 4</div>
</Carousel>
<a href="/about">Go to About page</a>
```

The `/about` link does not work producing the above error.

**Comment by antony** [comment]
Closing in favour of https://github.com/beyonk-adventures/svelte-carousel/issues/35 which I've been able to reproduce. This is certainly a bug.
