### ISSUE TITLE
Dots no active using right button

### ISSUE THREAD

**Issue by ProxyJoshua** [beyonk-adventures/svelte-carousel#27]
When the right button is used last 2 dots doesn't get active class
i have the solution but i dont know how to do a pull request

**Comment by antony** [comment]
Sounds great! Have a read of https://opensource.com/article/19/7/create-pull-request-github and let's get this merged in!

**Comment by johnyvelho** [comment]
I believe this is related to #36 which is working now. I tested and it seems to be working normally.
