### ISSUE TITLE
perPage working but with error message

### ISSUE THREAD

**Issue by ederby** [beyonk-adventures/svelte-carousel#39]
The perPage function used like "perPage={{ 800: 3, 500: 2 }}" generates an error message "Invalid array length" and even though it works as expected it fucks up other functions on the site.
![Skärmavbild 2020-06-25 kl  09 57 49](https://user-images.githubusercontent.com/46708729/85680193-5b527100-b6ca-11ea-858c-d5d0a537e652.png)

**Comment by antony** [comment]
It's useful if you tell me which version of the software you're using. I suspect this https://github.com/beyonk-adventures/svelte-carousel/pull/38 fixes your issue.

**Comment by ederby** [comment]
Wow it did worked! Thank you! :D
