### ISSUE TITLE
Not working with an each loop inside of it

### ISSUE THREAD

**Issue by Noureldineadel65** [beyonk-adventures/svelte-carousel#41]
I tried it with an each loop inside of it and it gave me this: siema.min.js:1 Uncaught TypeError: Cannot read property 'cloneNode' of undefined

**Comment by antony** [comment]
@Noureldineadel65 please can you provide a REPL demonstrating the issue :)

**Comment by Noureldineadel65** [comment]
I tried inside a REPL and it worked but when I wrap my each loop in my site with the Carousel component it gives me this issue and breaks my whole site, then gets back to normal when i remove the Carousel component.

![Annotation 2020-06-27 165240](https://user-images.githubusercontent.com/51364599/85925179-fc8e2280-b896-11ea-8762-2d0b5bf4422b.png)

**Comment by antony** [comment]
Unfortunately I can't diagnose an issue from a screenshot. Can you use the sapper template to create a reproduction I can try please?

**Comment by Noureldineadel65** [comment]
https://svelte.dev/repl/a2c392b6875247b29a9b22e7dc3946b7?version=3.23.2

**Comment by johnyvelho** [comment]
@Noureldineadel65 this is a bug, but easy to solve while there is no PR for it.
The default value for perPage is 3. And in this example you sent, there are only 2 items. which means that perPage(3) is bigger than the available items(2)

To solve it, all you need to do is inform the value for perPage. like this: https://svelte.dev/repl/fe8f8199470b4183a0625afe2fe865b6?version=3.23.2

**Comment by Noureldineadel65** [comment]
@johnyvelho Alright thanks a lot! I will close this
