### ISSUE TITLE
<Carousel> is not a valid SSR component.

### ISSUE THREAD

**Issue by vedmant** [beyonk-adventures/svelte-carousel#48]
When using with Sapper I have this error: 
<Carousel> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Would be nice to have some instructions how to use it with Sapper

**Comment by antony** [comment]
The install instructions are for Sapper, I've never used it with anything other than Sapper.

It sounds like you've installed the library as a regular dependency, not a dev dependency as instructed on the README.

Reinstall it as a dev dependency and the carousel should work.

**Comment by riez** [comment]
Hi @antony, 

I'm using sapper ^0.29.0 and has been installed it under devDependencies. I also getting this error message.
