### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by s0kil** [beyonk-adventures/svelte-carousel#5]
Would be great to be able to customize default control colors.

For example:
```js
export default {
	data() {
		carouselControlsButtonColor: "rgba(255, 255, 255, 0)";
	}
	components: {
		Carousel,
		Slide
	}
};
```
And `Carousel` would inherit those properies.

**Comment by antony** [comment]
@DanielSokil agreed. Right now I think you can do it with styling and :global ?

**Comment by antony** [comment]
Closing since the official way to do this is via global.
