### ISSUE TITLE
TypeError: Siema is not a constructor

### ISSUE THREAD

**Issue by Looease** [beyonk-adventures/svelte-carousel#78]
Hello. 
I have a Svelte app and have recently updated my `"rollup-plugin-svelte"` to  `"6.1.1"`. Since doing this, the Carousel is no longer rendering and I am seeing the below error. 

Do you have any fixes for this?
<img width="677" alt="Screenshot 2022-02-11 at 11 57 42" src="https://user-images.githubusercontent.com/40807466/153588024-ec261eae-80c4-42d2-a614-2e7ca8a6b27f.png">

<img width="764" alt="Screenshot 2022-02-11 at 12 01 50" src="https://user-images.githubusercontent.com/40807466/153588129-4fbdbc29-de1f-484c-8f23-9557b666a127.png">

**Comment by thobson** [comment]
Same for me

**Comment by mkaski** [comment]
Fixed in https://github.com/beyonk-adventures/svelte-carousel/pull/79

**Comment by inspiredlabs** [comment]
The REPL throws: `Siema is not a constructor`: https://svelte.dev/repl/3953567d530b41d087ab7eaa8e7e632a?version=3.22.3

This might be off-putting if people don't confirm for themselves, as I have this is indeed fixed.

**Comment by jeremybradbury** [comment]
I just got finished wiring my component wrapper up to the database / fileserver... and ofc there is some critical/breaking bug for the tool I chose.

@mkaski TYVM for fixing this! I hope we can get it approved and merged so I can get this code out of my dev environment, a custom developer build isn't going to make it to even a staging server over here.
