### ISSUE TITLE
Maintenance of Siema is discontinued

### ISSUE THREAD

**Issue by mcmxcdev** [beyonk-adventures/svelte-carousel#81]
There is a deprecation notice in the readme: https://github.com/pawelgrzybek/siema#readme 

No new commit has been done since Jan 2021.

**Comment by antony** [comment]
It was when I started the project :D

It works enough, and tbh this carousel is no longer used by us so is, in itself, somewhat in maintenance mode.

**Comment by mcmxcdev** [comment]
Then I would recommend adding a deprecation notice to this project itself. Otherwise, people assume that this project will receive regular maintenance, but they end up with open issues, outdated dependencies etc.

I am using https://github.com/Splidejs/svelte-splide now, which is a great alternative. You could provide a link to that carousel implementation.
